// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:5e3f1a38-6023-4a7b-ab67-5c7cf3b9bb0a',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'serverless-hosting-mobilehub-1594246059',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd44ydewkb23b4.cloudfront.net',
    'aws_mobile_analytics_app_id': '0da417d24b9b4d82b21229311688eee5',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e3ac4366-8de0-4b9a-98d7-c5134e222606',
    'aws_project_name': 'serverless',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'serverless-mobilehub-1594246059',
}

export default awsmobile;
